all: withPipeandFIFO

withPipeandFIFO: HW3_161044086_EFKAN_DURKLI.o
	gcc HW3_161044086_EFKAN_DURKLI.o -o withPipeandFIFO

main.o: HW3_161044086_EFKAN_DURKLI.c
	gcc -c HW3_161044086_EFKAN_DURKLI.c

clean:
	rm *.o withPipeandFIFO
